# References https://gist.github.com/dan-blanchard/7045057
# and https://docs.travis-ci.com/user/trusty-ci-environment/

sudo: false
dist: trusty

branches:
  only:
    - master

matrix:
  include:
    - env: PYTHON=2.7 CONDA_PY=27
    - env: PYTHON=3.5 CONDA_PY=35
    - env: PYTHON=3.6 CONDA_PY=36

before_install:

  # Install Miniconda
  - travis_retry wget -q https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH

  # Setup environment
  - travis_retry conda update --yes conda
  - conda config --set always_yes yes
  - conda config --append channels exopy
  - conda install conda-build anaconda-client -q
  - conda info -a
  - conda create -n travisci --yes python=$PYTHON pip
  - source activate travisci
  - CONDA_INSTALL="conda install -q"
  - PIP_INSTALL="pip install -q"

  # Setup conda build output directory
  - cd ~
  - mkdir conda-bld-out
  - cd conda-bld-out
  - export CONDA_BLD_PATH=$(pwd)

  # Install exopy dependencies
  - $CONDA_INSTALL pyqt numpy exopy h5py exopy_pulses pyclibrary
  - $CONDA_INSTALL pyvisa -c conda-forge

  # Intall test tools
  - $CONDA_INSTALL pytest
  - $PIP_INSTALL pytest-cov pytest-catchlog pytest-timeout

install:

  # Install exopy_hqc_legacy
  - cd $TRAVIS_BUILD_DIR
  # Needed to install pyvisa for testing purposes
  - conda config --append channels conda-forge
  - conda build conda -q  # Package building does run only very minimal tests
  - conda install exopy_hqc_legacy --use-local -q --override-channels
  - cd ~

before_script:
# I need a (fake) display on Travis so I need to start a X server.
- export DISPLAY=:99.0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
  # Run the exopy-hqc-legacy test suite
  - cd $TRAVIS_BUILD_DIR
  - py.test tests

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then bash continuous-integration/deploy.sh; fi
